<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Bons de commandes</title>
    <link rel="stylesheet" href="Assets/css/style.css" type="text/css" />
</head>
<body>
    <a href="index.php">Retourner à la liste des commandes</a>
    
 <h1>Bon commande n°<?= $data ?></h1>

    <div class="right">
        <p>
            <strong><?= $customer['customerName'] ?></strong>
        </p>
        <p>
           <strong> <?= $customer['contactFirstName'] ?> 
            <?= $customer['contactLastName'] ?></strong>
        </p>
        <p>
            <?= $customer['addressLine1'] ?> 
        </p>
        <p>
             <?= $customer['addressLine2'] ?>
        </p>
        <p>
             <?= $customer['city'] ?>  
        </p>
        <p>    
            <?= $customer['country'] ?>
        </p>
    </div>
    
    
    <table>
         <thead class="vert">
          <tr>
              <th>Produit</th>
               <th>Prix Unitaire</th>
               <th>Quantité</th>
               <th> Prix Total</th>
          </tr>
      </thead>
      <tbody>
          <?php foreach($orders as $order): ?>
           <tr>
            <td class="left"> <?= $order['nameProduct'] ?> </td>
            <td> <?= $order['priceEach'] ?> </td>
            <td> <?= $order['quantityOrdered'] ?> </td>
            <td> <?= $order['Prix Total'] ?> </td>
            <?php endforeach; ?>
        </tr> 
      </tbody>
      <tfoot>
          <tr>
              <td colspan="3" class="vert right">Montant Total HT</td>
              <td> <?= $tva['htPrice'] ?> </td>
           </tr>
            <tr>
                <td colspan="3" class="vert right">TVA(20%)</td>
                <td> <?= $tva['tva'] ?> </td>  
              </tr>
            <tr>
                <td colspan="3" class="vert right">Montant Total TTC</th>
                <td> <?= $tva['ttcPrice'] ?> </td>
                 
            </tr>
      </tfoot>
    </table>
    
</body>
</html>